### ISSUE TITLE
Bug: nach Schließen über "short-cut icon" im falschen Panel

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-dcawizard#15]
Hallo,

Beispiel beim NC:

* E-Mail-Konfiguration A öffnen
* Button "Sprachen verwalten" => eine Sprache editieren
* alles schließen

* E-Mail-Konfiguration B öffnen
* short-cut icon für eine Sprache anlicken und Speichen + Schließen
=> nun ist man wieder im Panel von E-Mail-Konfiguration A

Klickt man bei E-Mail-Konfiguration B auf Button "Sprachen verwalten" und geht zu A das Gleiche... es der Rücksprung erfolgt immer zu dem Panel, welches als letztes per "Sprachen verwalten" geöffnet wurde.

Da in dem Panel keine weiteren Angaben sind, fällt das nur anhand der E-Mail-Inhalte auf.

Gruss

~~~~~~~~~~~~~~~
dcawizard 	2.3.0 	4

**Comment by qzminski** [comment]
Fixed in ed05645.
