### ISSUE TITLE
[2.3.3] Weiterleitung beim Löschen

### ISSUE THREAD

**Issue by Tastaturberuf** [terminal42/contao-dcawizard#16]
An der Stelle erstmal großes Lob und vielen Dank für die super Erweiterung.

Ich habe beim Löschen von Datensätzen das Problem, das man auf den Inhalt des modal Fensters weitergeleitet wird. 

![modal_or_not_modal_that_is_the_question](https://cloud.githubusercontent.com/assets/1027521/13585187/a4b54d54-e4ba-11e5-9628-3392fffa6c26.PNG)

Ich hätte für euch Zugang auf den DEV-Server, falls Ihr euch das mal anschauen wollt.

**Comment by Toflar** [comment]
Das ist ein Problem des Referers. Die "zurück"-Funktion von Contao sucht ja in der Session nach dem Inhalt wo du zuletzt warst und leitet dich dann auf diese URL weiter. Das haben wir schon x-Mal versucht zu beheben, indem wir die Session verändern wollten. Aber irgendwie haben wir nie alle Fälle abdecken können und irgendwie haben wir's dann einfach aufgegeben. Pull Requests welcome, aber für uns ist das ein Wontfix bis sich jemand so sehr daran stört und uns mit der Bugsuche beauftragt. Aber freiwillig wollte sich das bisher keiner antun, sorry :-)
