### ISSUE TITLE
ajaxClass can have entities

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-dcawizard#20]
https://github.com/terminal42/contao-dcawizard/blob/e33b75752ee3d9a3f7a01e5e9e4c8b948688d566/classes/DcaWizardHelper.php#L89

to implement a dcaWizard, which will be translateable, we registered a new ``BE_FFL`` which extends ``DcaWizard``.

the concept with reflection in the ``DcaWizardHelper`` is very nice but unfortunately the base64-encoded classname can have entities. so the encoding should be changed or the line should be replaced by something like: ``$ajaxClass = \Input::post('class', true)``

**Comment by Toflar** [comment]
Ping @richardhj - I just stumbled over this old issue. Can you check if that issue still exists when you release a new version with the button callback fixes?

**Comment by richardhj** [comment]
Fixed in c809a848a55dea274e9ac10de7bf61054af42b85.

Using `\Input::post('class', true)` should help to keep special characters (like the `=` in `TXlEY2FXaXphcmQ=`).
