### ISSUE TITLE
Wrong label + title for Operation

### ISSUE THREAD

**Issue by rabauss** [terminal42/contao-dcawizard#24]
I guess since Contao 4.9 the label + title of the operations do not work anymore, because the label is no array here:
https://github.com/terminal42/contao-dcawizard/blob/5ddabcafa42ec53476718c7cc6e8fd501674a3e1/widgets/DcaWizard.php#L208-L209

A possible solution would be:
````php
        if (is_array($def['label'])) {
            $label = $def['label'][0] ?: $operation;
            $title = sprintf($def['label'][1] ?: $operation, $id);
        } else {
            $label = $title = sprintf($def['label'] ?: $operation, $id);
        }
````

**Comment by aschempp** [comment]
Why is there no label? As far as I know, Contao does set the global labels if the DCA does not have them?
