### ISSUE TITLE
Can't use hideButton setting together with listCallback

### ISSUE THREAD

**Issue by jelomada** [terminal42/contao-dcawizard#27]
Hi!
When use "listCallback" method than "hideButton" setting doesn't work. 
This is caused by placing this: `$objTemplate->hideButton = $this->hideButton;` inside of this "if":  `if ($varCallback === null) {`
https://github.com/terminal42/contao-dcawizard/blob/7e7e50ce9e05b203b644cb7fa7bfed53c44a3de2/widgets/DcaWizard.php#L161

Unfortunately I don't have time for placing pull request right now. 

Please fix this :)  Great ext BTW.

**Comment by Toflar** [comment]
> Unfortunately I don't have time for placing pull request right now.
> 
> Please fix this :) Great ext BTW.

Jeez, what's wrong with this world? 🤦‍♂️

**Comment by jelomada** [comment]
I've already override this in my project so I don't really need this fix. 
If you don't want to, you don't need to do anything. It's your ext and your choice. 

I've shown you a bug in your code and instead of saying "thanks man" you are unhappy about it. So answering the question: 
> Jeez, what's wrong with this world? 
Mostly everything :)

**Comment by fritzmg** [comment]
> I've shown you a bug in your code and instead of saying "thanks man" you are unhappy about it.

It's about your attitude. No one will take issue with bug reports otherwise.

**Comment by jelomada** [comment]
Maybe I've misspoken. By "pls fix this" i meant for others, for future releases etc. As I said - I don't need this for me. 
So whatever. Think what you want to think. 
Have a good day.

**Comment by Toflar** [comment]
I thought it was obvious but apparently it's not, so here goes the explanation:
Thank you for reporting an issue. I appreciate that. I'm not unhappy about the fact that you reported it, I'm unhappy about how you did it.
You are saying that you do not have the time for a PR and you ask me to fix it for you. This implies that your time is more important or more precious than mine. This is pretty rude and I'm not going to let anybody get away with it. Simple as that.
I know you probably didn't mean it like that, so here are a few ideas on how you could've submitted the issue instead:

> Unfortunately, I currently lack the time to submit a PR. I still decided to leave the issue here so that we do not forget about it. I'll try to come back to it in the future to provide a PR to fix it in case nobody else did until then.

> I'm sorry that I cannot provide a PR right away, I lack the knowledge to fix it myself. If you can point me in the right direction, maybe I can try to understand and help you out.

Both of them would've worked out just fine, I'm sure :)
Maybe you can consider writing something along those lines for your next bug report anywhere on the Internet. But of course, you're free to ignore my advice :)

Anyway, everything's been said. I'll leave the issue open, maybe someone actually does find the time to fix it some day.
Have a nice weekend!
