### ISSUE TITLE
Feature: Template-Option in DCA settings

### ISSUE THREAD

**Issue by OMOSde** [terminal42/contao-dcawizard#30]
How about an additional option 'template' in the DCA, so that you could use for example a customized 'be_widget_dcawizard'.

There is the listCallback, but there you have to take care of the display for the most part yourself (even if the widget is present as a parameter). 

UseCase

We have a larger project in which we use the dcawizard. Currently I would like to need 2 slightly different customized views.

You could maybe just add an alternative template here https://github.com/terminal42/contao-dcawizard/blob/3c4d7c138ad723434b0167dbcb859fb7b03b2108/widgets/DcaWizard.php#L152.

**Comment by Toflar** [comment]
Sure, we could name it `customTpl` so it's similar to the ones used in the FE. PR welcome :)

**Comment by OMOSde** [comment]
PR in https://github.com/terminal42/contao-dcawizard/pull/31/files

If something is missing or not included, please let me know.
