### ISSUE TITLE
Security issue: Sql-Injection possible in backend

### ISSUE THREAD

**Issue by koertho** [terminal42/contao-dcawizard#32]
A security audit from one of our costumers found a low security issue in notification center. It is possible to manipulate the message url so it shows all language entries. I could hunt the issue down to DcaWizard widget 

Append following to the contao url (id must be an existing one): `/contao?act=edit&do=nc_notifications&id=1%20or%20true&table=tl_nc_message`

The result: 
![image](https://user-images.githubusercontent.com/12064642/190376406-e9d70cc7-34e8-4862-94bb-c48d0f08c830.png)

If the the ID exist, it passes DC_Table here: https://github.com/contao/contao/blob/9f87d568209ba12d23734ce8f1cbbefc3900abef/core-bundle/src/Resources/contao/drivers/DC_Table.php#L1757 (maybe this is an issue in the contao core to?).
Afterward it builds following query in DcaWizard: `SELECT * FROM tl_nc_language WHERE tstamp>0 AND pid=1 or true ORDER BY language` (DcaWizard::getRecords())

**Versionen:**
Contao: 4.9.33 || 4.13.6
Notification Center: 1.6.13 || 1.6.14
DcaWizard: 2.5.0
PHP 7.4 || 8.1

**Comment by aschempp** [comment]
Fixed in a152744ade4be3fb3c6dede6c78c7459b0149416 (2.7)
